{
  "candidate": "CVE-2023-46695",
  "description": "An issue was discovered in Django 3.2 before 3.2.23, 4.1 before 4.1.13, and 4.2 before 4.2.7. The NFKC normalization is slow on Windows. As a consequence, django.contrib.auth.forms.UsernameField is subject to a potential DoS (denial of service) attack via certain inputs with a very large number of Unicode characters.",
  "notes": {
    "mdeslaur": "is a windows-specific issue"
  },
  "priority": "medium",
  "cvss": {
    "nvd": " CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]"
  },
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-46695",
    "https://www.djangoproject.com/weblog/2023/nov/01/security-releases/",
    "https://docs.djangoproject.com/en/4.2/releases/security/",
    "https://groups.google.com/forum/#!forum/django-announce"
  ],
  "public_date": "2023-11-02 06:15:00 UTC",
  "packages": {
    "bionic": {
      "python-django": {
        "name": "python-django",
        "status": "ignored",
        "note": "end of standard support"
      }
    },
    "devel": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "esm-infra/bionic": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "esm-infra/xenial": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "focal": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "jammy": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "lunar": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "mantic": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "trusty": {
      "python-django": {
        "name": "python-django",
        "status": "ignored",
        "note": "end of standard support"
      }
    },
    "trusty/esm": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "windows only"
      }
    },
    "upstream": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "debian: Only an issue on windows"
      }
    },
    "xenial": {
      "python-django": {
        "name": "python-django",
        "status": "ignored",
        "note": "end of standard support"
      }
    }
  }
}
