{
	"candidate": "CVE-2024-5953",
	"description": "A denial of service vulnerability was found in the 389-ds-base LDAP server. This issue may allow an authenticated user to cause a server denial of service while attempting to log in with a user with a malformed hash in their password.",
	"priority": "medium",
	"bugs": [
		"https://bugzilla.redhat.com/show_bug.cgi?id=2292104"
	],
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2024-5953",
		"https://access.redhat.com/security/cve/CVE-2024-5953"
	],
	"public_date": "2024-06-18",
	"packages": {
		"devel": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"esm-apps/bionic": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"esm-apps/focal": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"esm-apps/jammy": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"esm-apps/noble": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"esm-apps/xenial": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"focal": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"jammy": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"mantic": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"noble": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		},
		"upstream": {
			"389-ds-base": {
				"name": "389-ds-base",
				"status": "needs-triage"
			}
		}
	}
}
