{
	"candidate": "CVE-2024-37568",
	"description": "lepture Authlib before 1.3.1 has algorithm confusion with asymmetric public keys. Unless an algorithm is specified in a jwt.decode call, HMAC verification is allowed with any asymmetric public key. (This is similar to CVE-2022-29217 and CVE-2024-33663.)",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N [7.5 HIGH]"
	},
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2024-37568",
		"https://github.com/lepture/authlib/issues/654",
		"https://github.com/lepture/authlib/commit/3bea812acefebc9ee108aa24557be3ba8971daf1 (v1.3.1)"
	],
	"public_date": "2024-06-11",
	"packages": {
		"devel": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "needs-triage"
			}
		},
		"esm-apps/jammy": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "needed"
			}
		},
		"esm-apps/noble": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "needed"
			}
		},
		"focal": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "DNE"
			}
		},
		"jammy": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "needed"
			}
		},
		"mantic": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "needed"
			}
		},
		"noble": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "needed"
			}
		},
		"upstream": {
			"python-authlib": {
				"name": "python-authlib",
				"status": "needs-triage"
			}
		}
	}
}
