{
  "candidate": "CVE-2018-18649",
  "description": "An issue was discovered in the wiki API in GitLab Community and Enterprise Edition before 11.2.7, 11.3.x before 11.3.8, and 11.4.x before 11.4.3. It allows for remote code execution.",
  "notes": {
    "msalvatore": "Affects GitLab CE/EE 11.3 and later."
  },
  "priority": "medium",
  "cvss": {
    "nvd": " CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H [9.8 CRITICAL]"
  },
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-18649",
    "https://about.gitlab.com/2018/10/29/security-release-gitlab-11-dot-4-dot-3-released/"
  ],
  "public_date": "2018-11-29 15:29:00 UTC",
  "packages": {
    "bionic": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "cosmic": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "devel": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "disco": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "eoan": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "esm-apps/xenial": {
      "gitlab": {
        "name": "gitlab",
        "status": "not-affected",
        "note": "code not present"
      }
    },
    "precise/esm": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "trusty": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "trusty/esm": {
      "gitlab": {
        "name": "gitlab",
        "status": "DNE"
      }
    },
    "upstream": {
      "gitlab": {
        "name": "gitlab",
        "status": "needs-triage"
      }
    },
    "xenial": {
      "gitlab": {
        "name": "gitlab",
        "status": "not-affected",
        "note": "code not present"
      }
    }
  }
}
