{
	"candidate": "CVE-2015-0220",
	"description": "The django.util.http.is_safe_url function in Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 does not properly handle leading whitespaces, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a crafted URL, related to redirect URLs, as demonstrated by a \"\\njavascript:\" URL.",
	"priority": "medium",
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-0220",
		"https://www.djangoproject.com/weblog/2015/jan/13/security/",
		"https://ubuntu.com/security/notices/USN-2469-1"
	],
	"assigned_to": "mdeslaur",
	"discovered_by": "Mikko Ohtamaa",
	"public_date": "2015-01-16 16:59:00 UTC",
	"public_date_at_usn": "2015-01-13",
	"packages": {
		"devel": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.6-1ubuntu3"
			}
		},
		"lucid": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.1.1-2ubuntu1.14"
			}
		},
		"precise": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.3.1-4ubuntu1.13"
			}
		},
		"trusty": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.1-2ubuntu0.6"
			}
		},
		"trusty/esm": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.1-2ubuntu0.6"
			}
		},
		"upstream": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.10"
			}
		},
		"utopic": {
			"python-django": {
				"name": "python-django",
				"status": "released",
				"note": "1.6.6-1ubuntu2.1"
			}
		}
	}
}
