{
	"candidate": "CVE-2010-3492",
	"description": "The asyncore module in Python before 3.2 does not properly handle unsuccessful calls to the accept function, and does not have accompanying documentation describing how daemon applications should handle unsuccessful calls to the accept function, which makes it easier for remote attackers to conduct denial of service attacks that terminate these applications via network connections.",
	"priority": "negligible",
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2010-3492",
		"http://bugs.python.org/issue6706"
	],
	"public_date": "2010-10-19 20:00:00 UTC",
	"packages": {
		"dapper": {
			"python2.6": {
				"name": "python2.6",
				"status": "DNE"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "DNE"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "DNE"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "DNE"
			}
		},
		"devel": {
			"python2.6": {
				"name": "python2.6",
				"status": "ignored"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "not-affected",
				"note": "2.7.2-1"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "DNE"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "not-affected",
				"note": "3.2.1~rc1-1"
			}
		},
		"hardy": {
			"python2.6": {
				"name": "python2.6",
				"status": "DNE"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "DNE"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "DNE"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "DNE"
			}
		},
		"jaunty": {
			"python2.6": {
				"name": "python2.6",
				"status": "DNE"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "DNE"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "DNE"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "DNE"
			}
		},
		"karmic": {
			"python2.6": {
				"name": "python2.6",
				"status": "DNE"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "DNE"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "ignored",
				"note": "end of life"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "DNE"
			}
		},
		"lucid": {
			"python2.6": {
				"name": "python2.6",
				"status": "ignored"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "DNE"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "ignored"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "DNE"
			}
		},
		"maverick": {
			"python2.6": {
				"name": "python2.6",
				"status": "ignored"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "ignored"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "ignored"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "DNE"
			}
		},
		"natty": {
			"python2.6": {
				"name": "python2.6",
				"status": "ignored"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "not-affected",
				"note": "2.7.1-5ubuntu2"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "not-affected",
				"note": "3.1.3-1ubuntu1"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "not-affected",
				"note": "3.2-1ubuntu1"
			}
		},
		"oneiric": {
			"python2.6": {
				"name": "python2.6",
				"status": "ignored"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "not-affected",
				"note": "2.7.2-1"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "DNE"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "not-affected",
				"note": "3.2.1~rc1-1"
			}
		},
		"upstream": {
			"python2.6": {
				"name": "python2.6",
				"status": "needed"
			},
			"python2.7": {
				"name": "python2.7",
				"status": "released",
				"note": "2.7.1 rc1"
			},
			"python3.1": {
				"name": "python3.1",
				"status": "released",
				"note": "3.1.3 rc1"
			},
			"python3.2": {
				"name": "python3.2",
				"status": "released",
				"note": "3.2"
			}
		}
	}
}
