{
	"candidate": "CVE-2020-13328",
	"description": "An issue has been discovered in GitLab affecting versions prior to 13.1.2, 13.0.8 and 12.10.13. GitLab was vulnerable to a stored XSS by using the PyPi files API.",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N [4.8 MEDIUM]"
	},
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2020-13328"
	],
	"public_date": "2020-09-30 18:15:00 UTC",
	"packages": {
		"bionic": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"devel": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"esm-apps/xenial": {
			"gitlab": {
				"name": "gitlab",
				"status": "needed"
			}
		},
		"esm-infra-legacy/trusty": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"focal": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"groovy": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"hirsute": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"impish": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"jammy": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"kinetic": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"lunar": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"mantic": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"noble": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"precise/esm": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"trusty": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"trusty/esm": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"upstream": {
			"gitlab": {
				"name": "gitlab",
				"status": "needs-triage"
			}
		},
		"xenial": {
			"gitlab": {
				"name": "gitlab",
				"status": "ignored",
				"note": "end of standard support, was needed"
			}
		}
	}
}
