{
	"candidate": "CVE-2020-11649",
	"description": "An issue was discovered in GitLab CE and EE 8.15 through 12.9.2. Members of a group could still have access after the group is deleted.",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N [6.5 MEDIUM]"
	},
	"references": [
		"https://about.gitlab.com/releases/2020/04/14/critical-security-release-gitlab-12-dot-9-dot-3-released/",
		"https://www.cve.org/CVERecord?id=CVE-2020-11649"
	],
	"public_date": "2020-04-22 20:15:00 UTC",
	"packages": {
		"bionic": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"devel": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"eoan": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"esm-apps/xenial": {
			"gitlab": {
				"name": "gitlab",
				"status": "not-affected",
				"note": "code not present"
			}
		},
		"esm-infra-legacy/trusty": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"precise/esm": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"trusty": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"trusty/esm": {
			"gitlab": {
				"name": "gitlab",
				"status": "DNE"
			}
		},
		"upstream": {
			"gitlab": {
				"name": "gitlab",
				"status": "needs-triage"
			}
		},
		"xenial": {
			"gitlab": {
				"name": "gitlab",
				"status": "not-affected",
				"note": "code not present"
			}
		}
	}
}
