{
	"candidate": "CVE-2020-29651",
	"description": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]"
	},
	"references": [
		"https://github.com/pytest-dev/py/issues/256",
		"https://github.com/pytest-dev/py/pull/257",
		"https://ubuntu.com/security/notices/USN-5138-1",
		"https://www.cve.org/CVERecord?id=CVE-2020-29651"
	],
	"public_date": "2020-12-09 07:15:00 UTC",
	"public_date_at_usn": "2020-12-09 07:15:00 UTC",
	"packages": {
		"bionic": {
			"python-py": {
				"name": "python-py",
				"status": "released",
				"note": "1.5.2-1ubuntu0.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"devel": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"esm-apps/bionic": {
			"python-py": {
				"name": "python-py",
				"status": "released",
				"note": "1.5.2-1ubuntu0.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"esm-apps/focal": {
			"python-py": {
				"name": "python-py",
				"status": "released",
				"note": "1.8.1-1ubuntu0.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"esm-apps/jammy": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"esm-apps/xenial": {
			"python-py": {
				"name": "python-py",
				"status": "needed",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"focal": {
			"python-py": {
				"name": "python-py",
				"status": "released",
				"note": "1.8.1-1ubuntu0.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"groovy": {
			"python-py": {
				"name": "python-py",
				"status": "ignored",
				"note": "end of life",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"hirsute": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"impish": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"jammy": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"kinetic": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"lunar": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"mantic": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"noble": {
			"python-py": {
				"name": "python-py",
				"status": "not-affected",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"precise/esm": {
			"python-py": {
				"name": "python-py",
				"status": "DNE",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"trusty": {
			"python-py": {
				"name": "python-py",
				"status": "ignored",
				"note": "end of standard support",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"trusty/esm": {
			"python-py": {
				"name": "python-py",
				"status": "DNE",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"upstream": {
			"python-py": {
				"name": "python-py",
				"status": "released",
				"note": "1.10.0-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		},
		"xenial": {
			"python-py": {
				"name": "python-py",
				"status": "ignored",
				"note": "end of standard support, was needs-triage",
				"patches": [
					{
						"source": "upstream",
						"text": "https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144"
					}
				]
			}
		}
	}
}
