{
  "candidate": "CVE-2011-4138",
  "description": "The verify_exists functionality in the URLField implementation in Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's validity through a HEAD request, but then uses a GET request for the new target URL in the case of a redirect, which might allow remote attackers to trigger arbitrary GET requests with an unintended source IP address via a crafted Location header.",
  "priority": "medium",
  "references": [
    "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-4138",
    "https://www.djangoproject.com/weblog/2011/sep/09/security-releases-issued/",
    "https://ubuntu.com/security/notices/USN-1297-1"
  ],
  "assigned_to": "jdstrand",
  "discovered_by": "Paul McMillan",
  "public_date": "2011-10-19 10:55:00 UTC",
  "public_date_at_usn": "2011-10-19",
  "packages": {
    "devel": {
      "python-django": {
        "name": "python-django",
        "status": "not-affected",
        "note": "1.3.1-1ubuntu1",
        "patches": [
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16766 (1.2)"
          },
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16763 (1.3)"
          }
        ]
      }
    },
    "hardy": {
      "python-django": {
        "name": "python-django",
        "status": "ignored",
        "note": "end of life",
        "patches": [
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16766 (1.2)"
          },
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16763 (1.3)"
          }
        ]
      }
    },
    "lucid": {
      "python-django": {
        "name": "python-django",
        "status": "released",
        "note": "1.1.1-2ubuntu1.4",
        "patches": [
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16766 (1.2)"
          },
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16763 (1.3)"
          }
        ]
      }
    },
    "maverick": {
      "python-django": {
        "name": "python-django",
        "status": "released",
        "note": "1.2.3-1ubuntu0.2.10.10.3",
        "patches": [
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16766 (1.2)"
          },
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16763 (1.3)"
          }
        ]
      }
    },
    "natty": {
      "python-django": {
        "name": "python-django",
        "status": "released",
        "note": "1.2.5-1ubuntu1.1",
        "patches": [
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16766 (1.2)"
          },
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16763 (1.3)"
          }
        ]
      }
    },
    "oneiric": {
      "python-django": {
        "name": "python-django",
        "status": "released",
        "note": "1.3-2ubuntu1.1",
        "patches": [
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16766 (1.2)"
          },
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16763 (1.3)"
          }
        ]
      }
    },
    "upstream": {
      "python-django": {
        "name": "python-django",
        "status": "released",
        "note": "1.3.1-1",
        "patches": [
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16766 (1.2)"
          },
          {
            "source": "upstream",
            "text": "https://code.djangoproject.com/changeset/16763 (1.3)"
          }
        ]
      }
    }
  }
}
