{
	"candidate": "CVE-2022-0718",
	"description": "A flaw was found in python-oslo-utils. Due to improper parsing, passwords with a double quote ( \" ) in them cause incorrect masking in debug logs, causing any part of the password after the double quote to be plaintext.",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N [4.9 MEDIUM]"
	},
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0718",
		"https://bugzilla.redhat.com/show_bug.cgi?id=2056850",
		"https://ubuntu.com/security/notices/USN-5369-1"
	],
	"assigned_to": "leosilva",
	"public_date": "2022-08-29 15:15:00 UTC",
	"public_date_at_usn": "2022-03-23 00:00:00 UTC",
	"packages": {
		"bionic": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "released",
				"note": "3.35.0-0ubuntu1.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"devel": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "not-affected",
				"note": "4.12.2-0ubuntu1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"esm-infra/bionic": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "released",
				"note": "3.35.0-0ubuntu1.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"esm-infra/xenial": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "released",
				"note": "3.8.0-2ubuntu0.1~esm1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"focal": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "released",
				"note": "4.1.1-0ubuntu1.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"impish": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "released",
				"note": "4.10.0-0ubuntu1.1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"jammy": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "not-affected",
				"note": "4.12.2-0ubuntu1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"trusty": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "ignored",
				"note": "end of standard support",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"upstream": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "released",
				"note": "4.10.1-1",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		},
		"xenial": {
			"python-oslo.utils": {
				"name": "python-oslo.utils",
				"status": "ignored",
				"note": "end of standard support",
				"patches": [
					{
						"source": "upstream",
						"text": "https://opendev.org/openstack/oslo.utils/commit/6e17ae1f7959c64dfd20a5f67edf422e702426aa"
					}
				]
			}
		}
	}
}
