{
	"candidate": "CVE-2022-42902",
	"description": "In Linaro Automated Validation Architecture (LAVA) before 2022.10, there is dynamic code execution in lava_server/lavatable.py. Due to improper input sanitization, an anonymous user can force the lava-server-gunicorn service to execute user-provided code on the server.",
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H [8.8 HIGH]"
	},
	"bugs": [
		"http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1021737"
	],
	"references": [
		"https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42902",
		"https://git.lavasoftware.org/lava/lava/-/merge_requests/1834",
		"https://git.lavasoftware.org/lava/lava/-/commit/e66b74cd6c175ff8826b8f3431740963be228b52?merge_request_iid=1834"
	],
	"public_date": "2022-10-13 03:15:00 UTC",
	"packages": {
		"bionic": {
			"lava": {
				"name": "lava",
				"status": "DNE"
			}
		},
		"devel": {
			"lava": {
				"name": "lava",
				"status": "not-affected",
				"note": "2023.01-2"
			}
		},
		"focal": {
			"lava": {
				"name": "lava",
				"status": "DNE"
			}
		},
		"jammy": {
			"lava": {
				"name": "lava",
				"status": "DNE"
			}
		},
		"kinetic": {
			"lava": {
				"name": "lava",
				"status": "DNE"
			}
		},
		"lunar": {
			"lava": {
				"name": "lava",
				"status": "not-affected",
				"note": "2023.01-2"
			}
		},
		"trusty": {
			"lava": {
				"name": "lava",
				"status": "ignored",
				"note": "end of standard support"
			}
		},
		"upstream": {
			"lava": {
				"name": "lava",
				"status": "released",
				"note": "2022.10-1"
			}
		},
		"xenial": {
			"lava": {
				"name": "lava",
				"status": "ignored",
				"note": "end of standard support"
			}
		}
	}
}
