{
	"candidate": "CVE-2021-28148",
	"description": "One of the usage insights HTTP API endpoints in Grafana Enterprise 6.x before 6.7.6, 7.x before 7.3.10, and 7.4.x before 7.4.5 is accessible without any authentication. This allows any unauthenticated user to send an unlimited number of requests to the endpoint, leading to a denial of service (DoS) attack against a Grafana Enterprise instance.",
	"notes": {
		"avital": "only affects the enterprise grafana version"
	},
	"priority": "medium",
	"cvss": {
		"nvd": " CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]"
	},
	"references": [
		"https://www.cve.org/CVERecord?id=CVE-2021-28148"
	],
	"public_date": "2021-03-22 15:15:00 UTC",
	"packages": {
		"bionic": {
			"grafana": {
				"name": "grafana",
				"status": "DNE"
			}
		},
		"devel": {
			"grafana": {
				"name": "grafana",
				"status": "DNE"
			}
		},
		"esm-apps/xenial": {
			"grafana": {
				"name": "grafana",
				"status": "not-affected"
			}
		},
		"focal": {
			"grafana": {
				"name": "grafana",
				"status": "DNE"
			}
		},
		"groovy": {
			"grafana": {
				"name": "grafana",
				"status": "DNE"
			}
		},
		"precise/esm": {
			"grafana": {
				"name": "grafana",
				"status": "DNE"
			}
		},
		"trusty": {
			"grafana": {
				"name": "grafana",
				"status": "ignored",
				"note": "end of standard support"
			}
		},
		"trusty/esm": {
			"grafana": {
				"name": "grafana",
				"status": "DNE"
			}
		},
		"upstream": {
			"grafana": {
				"name": "grafana",
				"status": "needs-triage"
			}
		},
		"xenial": {
			"grafana": {
				"name": "grafana",
				"status": "not-affected"
			}
		}
	}
}
